CREATE TABLE USUARIO(
NAME VARCHAR(20) NOT NULL,
DOUBLE MONTO
);

CREATE TABLE TIPO_CAMBIO(
NAME VARCHAR(20) NOT NULL,
CREATEAT DATE
);


CREATE TABLE MONEDA_ORIGEN(
NAME PAIS VARCHAR(20) NOT NULL,
CREATEAT DATE
);

CREATE TABLE TIPOCAMBIOPORMONEDAORIGENDOLARCONSOL(
ID DOUBLE TIPODECAMBIO,
ID DOUBLE MONEDAORIGEN,
);
   